version: '3.8'

services:
  nginx:
    image: dfactory01-docker.pkg.coding.net/01factory/release/nginx:latest
    environment:
      - NGINX_PORT=3456
    ports:
      - 3456:3456
    links:
      - 01factory-web:webserver

  01factory-web:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/01factory/release/web:dev
    volumes:
      - ./data/01factory:/01factory
      - ~/.ssh:/root/.ssh
    links:
      - 01factory-doccode:docode

  db:
    image: dfactory01-docker.pkg.coding.net/01factory/release/postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql

  01factory-doccode:
    image: dfactory01-docker.pkg.coding.net/01factory/release/doccode:latest
    volumes:
      - ./data/01factory:/01factory

  adminer:
    image: dfactory01-docker.pkg.coding.net/01factory/release/adminer:latest

  minio:
    image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
    volumes:
      - ./data/minio:/data

  # minio1:
  #   image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
  #   volumes:
  #     - ./data/minio11:/data1
  #     - ./data/minio12:/data2
  #   environment:
  #     - MINIO_ACCESS_KEY=mmstudio
  #     - MINIO_SECRET_KEY=mmstudio
  #   command: |
  #     server --console-address :9001 http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2

  # minio2:
  #   image: dfactory01-docker.pkg.coding.net/01factory/release/minio:latest
  #   volumes:
  #     - ./data/minio21:/data1
  #     - ./data/minio22:/data2
  #   environment:
  #     - MINIO_ACCESS_KEY=mmstudio
  #     - MINIO_SECRET_KEY=mmstudio
  #   command: |
  #     server --console-address :9001 http://minio1/data1 http://minio1/data2 http://minio2/data1 http://minio2/data2

  mc:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/01factory/release/mc:latest
    volumes:
      - ./data/mc:/root/.mc
      - ./data/files:/01factory

  fileview:
    image: dfactory01-docker.pkg.coding.net/01factory/release/fileview:latest
    volumes:
      - ./data/01factory:/01factory
    links:
      - 01factory-web:webserver
