import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head'
import Link from 'next/link';
import pages from '../atoms/pages'

// 所有页面路由数据接口
interface IProps {
  pages: string[];
}

const Home: NextPage<IProps> = ({ pages }) => {
  return (
    <>
      <Head>
        <title>Next-11</title>
      </Head>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <h1>开发页面</h1>
        {
          pages.map((row) => {
            return <li key={row}>
              <Link href={row}>{row}</Link>
            </li>
          })
        }
      </div>
      <style jsx>{`
        .home {
            margin: 50px 0 0 100px;
        }
        h1 {
            margin: 30px 0;
        }
        li {
            list-style: none;
            font: normal 22px/22px normal;
            margin: 20px 0;
        }
        
    `}</style>
    </>
  )
}

export default Home;

// 获取所有的页面路由
export const getServerSideProps: GetServerSideProps<IProps> = async (context) => {
  console.log(process.env.NODE_ENV);
  const pagesRouter = (() => {
    if (process.env.NODE_ENV === "development") {
      return Object.keys(pages);
    }
    return [];
  })();
  // 第二种重定向
  if (!pagesRouter.length) {
    return {
      redirect: {
        destination: "/home",
        permanent: false
      }
    }
  }
  return {
    props: {
      pages: pagesRouter
    }
  }
}